# phpIPAM (PHP-FPM) with nginx stack
version: '3'
services:

  app:
    build: .
    image: networkmgmt/phpipam
    links:
      - database
    volumes:
      - nginx_docs:/var/www/html/:rw
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      PHPIPAM_MYSQL_PASSWORD: "phpipamadmin"
    restart: always

  nginx:
    image: nginx:1.13-alpine
    links:
      - app
    ports:
      - 8000:80
    volumes:
      - nginx_docs:/var/www/html/:rw
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      VIRTUAL_HOST: "ipam.example.com"
    restart: always

  database:
    image: mariadb:10.2
    volumes:
      - ~/.database/phpipam/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "phpipamadmin"
    restart: always

networks:
  default:

volumes:
  nginx_docs:
    driver: local
