---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: phpipam-backup-db-pv-claim
  namespace: phpipam
  labels:
    app.kubernetes.io/name: phpipam
    app.kubernetes.io/instance: my-phpipam
    app.kubernetes.io/component: phpipam-db-utils
spec:
  storageClassName: nfs-client-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
